version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 6
    target-branch: "main"
    ignore:
      - dependency-name: "*storybook*" # ignore all storybook packages
