name: setup-node
description: setup node and install packages

inputs:
  check-package:
    description: 'Check package'
    default: false

runs:
  using: composite
  steps:
    # Extracts the major version from the last version range in engines.node (e.g. >=22.0.0 <23.0.0 || >=24.0.0 <25.0.0 => 24)
    # This allows the CI to always use the latest declared LTS without changing the workflow for each new LTS
    - name: Get Node.js LTS major version from engines (last range)
      shell: bash
      run: |
        NODE_RANGE=$(jq -r .engines.node package.json | awk -F ' *\\|\\| *' '{print $NF}')
        NODE_MAJOR=$(echo "$NODE_RANGE" | grep -oE '[0-9]+' | head -1)
        echo "NODE_VERSION=$NODE_MAJOR" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        registry-url: "https://registry.npmjs.org"
        node-version: ${{ env.NODE_VERSION || 'lts/*' }}

    - name: Check package
      if: inputs.check-package
      run: npm run package:check
      shell: bash

    - name: Install package
      run: npm ci
      shell: bash
