name: setup-node
description: setup node and install packages

inputs:
  check-package:
    description: 'Check package'
    default: false

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: "*" # Use the LTS Node.js version
        cache: "npm"
        registry-url: "https://registry.npmjs.org"

    - name: Check package
      if: inputs.check-package
      run: npm run package:check
      shell: bash

    - name: Install package
      run: npm ci
      shell: bash
