name: setup-node
description: setup node and install packages

inputs:
  check-package:
    description: 'Check package'
    default: false

runs:
  using: composite
  steps:
    - name: Get Node.js version from volta
      shell: bash
      run: echo "NODE_VERSION=$(jq -r .volta.node package.json)" >> $GITHUB_ENV
    
    - name: Get npm version from volta
      shell: bash
      run: echo "NPM_VERSION=$(jq -r .volta.npm package.json)" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        registry-url: "https://registry.npmjs.org"
        node-version: ${{ env.NODE_VERSION || 'lts/*' }}

    - name: Setup npm version
      if: ${{ env.NPM_VERSION }}
      shell: bash
      run: npm install -g npm@${{ env.NPM_VERSION }}

    - name: Check package
      if: inputs.check-package
      run: npm run package:check
      shell: bash

    - name: Install package
      run: npm ci
      shell: bash
