name: create-storybook-artifact
description: Create artifact storybooks

inputs:
  folders:
    description: 'List of artifact folder names (e.g., "apollo/react,look-and-feel/react,look-and-feel/css")'
    required: true
  artifact-name:
    description: 'Name of the artifact to be created'
    required: true

runs:
  using: composite
  steps:
    - name: Create artifact folders and move storybooks
      shell: bash
      run: |
        IFS=',' read -r -a folders <<< "${{ inputs.folders }}"
        for folder in "${folders[@]}"; do
          app="apps/${folder%%/*}-stories-${folder#*/}/storybook-static/*"
          app=$(echo "$app" | sed 's/-react//')
          artifact="artifact/$folder"
          mkdir -p $artifact
          cp -R $app $artifact
        done

    - name: Upload ${{ inputs.artifact-name }} artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ inputs.artifact-name }}
        path: artifact
        retention-days: 2
