blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://support.github.com
    about: Check out our Community Support for help with non-bug related issues.
issue_templates:
  - name: Slash Bug report
    about: Create a report to help us improve Slash Design System
    labels: 
      - bug
      - agent-slash
    template: bug_report.md
  - name: Look&Feel Bug report
    about: Create a report to help us improve Look&Feel Design System
    labels: 
      - bug
      - look'n feel (Espace Client)
    template: bug_report.md
  - name: Apollo Bug report
    about: Create a report to help us improve Apollo Design System
    labels: 
      - bug
      - Apollo AXA.fr
    template: bug_report.md
  - name: Slash Accessibility report
    about: Create an accessibility report to help us improve Slash Design System
    labels: 
      - bug
      - accessibility
      - agent-slash
    template: accessibility_issue.md
  - name: Look&Feel Bug report
    about: Create an accessibility report to help us improve Look&Feel Design System
    labels: 
      - bug
      - accessibility
      - look'n feel (Espace Client)
    template: accessibility_issue.md
  - name: Apollo Bug report
    about: Create an accessibility report to help us improve Apollo Design System
    labels: 
      - bug
      - accessibility
      - Apollo AXA.fr
    template: accessibility_issue.md