name: Publish Client

on:
  push:
    branches:
      - "releases-client/*"
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    if: github.repository_owner == 'AxaFrance'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.fullSemVer }}
      isStableRelease: ${{ steps.gitversion.outputs.preReleaseTag == '' }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@441c43ddefe9c8f5b8e8cee0257bcf06d518d2d3 # v3.2.0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@441c43ddefe9c8f5b8e8cee0257bcf06d518d2d3 # v3.2.0
        with:
          useConfigFile: true
          configFilePath: "GitVersion-client.yml"

      - name: Check package
        run: npm run package:check
      - name: Install package
        run: npm ci

      - name: build
        run: |
          npm run build:apollo
          npm run build:look-and-feel

      - run:
          npm version "${{ steps.gitversion.outputs.fullSemVer }}" -w
          client/apollo/css -w client/apollo/react -w
          client/look-and-feel/css -w client/look-and-feel/react

      - name: Update package.json
        run: |
          node scripts/pre-publish.js client

      - name: Publish packages
        run: |
          if [ "${{ steps.gitversion.outputs.preReleaseTag }}" = "" ]; then
            npm publish -w client/apollo/css -w client/apollo/react -w client/look-and-feel/css -w client/look-and-feel/react --access public --tag latest;
          else
            npm publish -w client/apollo/css -w client/apollo/react -w client/look-and-feel/css -w client/look-and-feel/react --access public --tag next;
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: create artifact folder
        run: |
          mkdir -p artifact/apollo/react
          mkdir -p artifact/look-and-feel/css
          mkdir -p artifact/look-and-feel/react
      - name: move storybooks to artifact folders
        run: |
          cp -R apps/apollo-stories/storybook-static/* artifact/apollo/react
          cp -R apps/look-and-feel-stories-css/storybook-static/* artifact/look-and-feel/css
          cp -R apps/look-and-feel-stories/storybook-static/* artifact/look-and-feel/react
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: storybooks
          path: |
            artifact
          retention-days: 2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy new version of storybook to gh-pages
    strategy:
      matrix:
        storybook:
          - name: apollo react
            publish_dir: ./apollo/react
            destination_dir: apollo/react
          - name: look-and-feel react
            publish_dir: ./look-and-feel/react
            destination_dir: look-and-feel/react
          - name: look-and-feel css
            publish_dir: ./look-and-feel/css
            destination_dir: look-and-feel/css
        version:
          - next
          - latest
          - ${{ needs.build.outputs.version }}
      max-parallel: 1

    steps:
      - name: Download storybooks
        if: needs.build.outputs.isStableRelease == 'true' || matrix.version == 'next'
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: storybooks

      - name: Upload the ${{ matrix.storybook.name }} storybook version ${{ matrix.version }}
        if: needs.build.outputs.isStableRelease == 'true' || matrix.version == 'next'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ matrix.storybook.publish_dir }}
          destination_dir: ${{ matrix.storybook.destination_dir }}/${{ matrix.version }}
